use super::*;

impl JsRuntime {
    pub(super) fn call_query_inner(
        &self,
        id: CallbackId,
        state: &State,
    ) -> Result<Vec<Hap>, String> {
        with_ctx(&self.ctx, |ctx| {
            Self::with_callback(&ctx, id, |f| {
                let controls = rquickjs::Object::new(ctx.clone())
                    .map_err(|error| describe_js_error(&ctx, error))?;
                for (k, v) in &state.controls {
                    controls
                        .set(
                            k.as_str(),
                            to_js(&ctx, v).map_err(|error| describe_js_error(&ctx, error))?,
                        )
                        .map_err(|error| describe_js_error(&ctx, error))?;
                }
                let stack = host_stack(&ctx).map_err(|error| describe_js_error(&ctx, error))?;
                let obj: rquickjs::Object =
                    match stack.as_object().get::<_, Function>(STATE_FACTORY) {
                        Ok(state_factory) => state_factory
                            .call((
                                span_seed(&ctx, state.span)
                                    .map_err(|error| describe_js_error(&ctx, error))?,
                                controls,
                            ))
                            .map_err(|error| describe_js_error(&ctx, error))?,
                        // GraphBuilder's low-level callback tests intentionally do
                        // not install the semantic surface. Preserve their compact
                        // state shape; product/new-Pattern routes always use the
                        // real State/TimeSpan/Fraction factory above.
                        Err(_) => {
                            let state_object = rquickjs::Object::new(ctx.clone())
                                .map_err(|error| describe_js_error(&ctx, error))?;
                            let span = rquickjs::Object::new(ctx.clone())
                                .map_err(|error| describe_js_error(&ctx, error))?;
                            span.set("begin", state.span.begin.to_f64())
                                .map_err(|error| describe_js_error(&ctx, error))?;
                            span.set("end", state.span.end.to_f64())
                                .map_err(|error| describe_js_error(&ctx, error))?;
                            state_object
                                .set("span", span)
                                .map_err(|error| describe_js_error(&ctx, error))?;
                            state_object
                                .set("controls", controls)
                                .map_err(|error| describe_js_error(&ctx, error))?;
                            state_object
                        }
                    };

                // `describe_js_error`, not `to_string`: `to_string` yields
                // "Exception generated by QuickJS" for every JS failure, so
                // heap exhaustion and an ordinary user throw would have the
                // same text.
                let out: rquickjs::Value = f
                    .call((obj,))
                    .map_err(|error| describe_js_error(&ctx, error))?;
                let arr = out
                    .as_array()
                    .ok_or("query callback must return an array")?;
                // Not refused on `arr.len()`. A declared length is not a hap
                // count: `Array(50_000)` with three elements set converts to
                // three haps, and rejecting it would refuse work the budget
                // permits. An early length check would also hide a broken
                // per-push check.
                //
                // Converted haps are what count, charged below as they are
                // made. The one length refused up front is one `iter()` cannot
                // read: it asserts the length fits an `i32` and PANICS past it
                // (see `js_array_len`), and no hap budget reaches that far.
                if js_array_len(arr).map_err(|error| describe_js_error(&ctx, error))?
                    > i32::MAX as usize
                {
                    return Err("query callback returned an array too long to read".into());
                }
                let mut haps = Vec::new();
                let mut hap_sidecars = Vec::new();
                // Every hap value is kept, so all of them draw on ONE
                // materialization budget: 64 haps sharing one sparse array
                // just under the cap must not reserve 64 heap ceilings.
                let materialize_budget = Cell::new(
                    js_element_cap::<Value>(&ctx)
                        .map_err(|error| describe_js_error(&ctx, error))?,
                );
                for item in arr.iter::<rquickjs::Object>() {
                    let item = match item {
                        Ok(item) => item,
                        Err(error) if matches!(error, rquickjs::Error::Exception) => {
                            return Err(describe_js_error(&ctx, error));
                        }
                        // Sparse holes convert from `undefined` to Object with
                        // a non-exception type error. They are absent haps, not
                        // query failures; preserve the established sparse-array
                        // contract while still consuming real getter throws.
                        Err(_) => continue,
                    };
                    // Charged per hap, as they are converted. A callback is a
                    // producer like any node: `new Pattern(() => hugeArray)`
                    // would otherwise materialise the whole thing here before
                    // anything could refuse it.
                    // The length this push WOULD reach, not a constant: the
                    // budget is a high-water bound on one vector, so charging 1
                    // each time asked whether one hap exceeds the budget and
                    // accepted every push.
                    if !rustel_core::charge_hap_at(haps.len() + 1) {
                        return Err(
                            "query callback exceeded the hap budget for this query".to_string()
                        );
                    }
                    // Host-created `Pattern.query` returns real pinned-shaped
                    // Hap objects (`part`/`whole`); the legacy builder route
                    // returns the compact `{begin,end,value}` shape. Accept
                    // both at this one conversion boundary.
                    let part_value: rquickjs::Value = item
                        .get("part")
                        .map_err(|error| describe_js_error(&ctx, error))?;
                    let part = part_value.as_object();
                    let b: Fraction = match &part {
                        Some(part) => fraction_property(&ctx, part, "begin")
                            .map_err(|error| describe_js_error(&ctx, error))?,
                        None => fraction_property(&ctx, &item, "begin")
                            .map_err(|error| describe_js_error(&ctx, error))?,
                    };
                    let e: Fraction = match &part {
                        Some(part) => fraction_property(&ctx, part, "end")
                            .map_err(|error| describe_js_error(&ctx, error))?,
                        None => fraction_property(&ctx, &item, "end")
                            .map_err(|error| describe_js_error(&ctx, error))?,
                    };
                    let val: rquickjs::Value = item
                        .get("value")
                        .map_err(|error| describe_js_error(&ctx, error))?;
                    let sp = rustel_core::TimeSpan::new(b, e);
                    let whole = if !item
                        .contains_key("whole")
                        .map_err(|error| describe_js_error(&ctx, error))?
                    {
                        // The legacy builder callback shape has no `whole`
                        // field and historically meant a discrete hap whose
                        // whole equals its part. A REAL Hap with an explicit
                        // undefined whole is analog; checking only `get`
                        // conflates missing with undefined in JavaScript.
                        Some(sp)
                    } else {
                        match item
                            .get::<_, rquickjs::Value>("whole")
                            .map_err(|error| describe_js_error(&ctx, error))?
                        {
                            value if value.is_undefined() || value.is_null() => None,
                            value => {
                                let object = value
                                    .as_object()
                                    .ok_or("query callback whole must be a TimeSpan")?;
                                let begin = fraction_property(&ctx, object, "begin")
                                    .map_err(|error| describe_js_error(&ctx, error))?;
                                let end = fraction_property(&ctx, object, "end")
                                    .map_err(|error| describe_js_error(&ctx, error))?;
                                Some(rustel_core::TimeSpan::new(begin, end))
                            }
                        }
                    };
                    let (value, sidecars) =
                        materialize_js_value_within(&ctx, &val, &materialize_budget)
                            .map_err(|error| describe_js_error(&ctx, error))?;
                    hap_sidecars
                        .try_reserve(sidecars.len())
                        .map_err(|_| "query callback sidecar allocation failed".to_string())?;
                    hap_sidecars.extend(sidecars);
                    let mut locations = Vec::new();
                    let context_value: rquickjs::Value = item
                        .get("context")
                        .map_err(|error| describe_js_error(&ctx, error))?;
                    if let Some(context) = context_value.as_object() {
                        let locations_value: rquickjs::Value = context
                            .get("locations")
                            .map_err(|error| describe_js_error(&ctx, error))?;
                        if let Some(array) = locations_value.as_array() {
                            // A score-authored length (see `js_array_len`).
                            // The walk visits every claimed slot and keeps a
                            // span per location, so the claim is charged to
                            // the budget every hap of this callback shares.
                            let locations_len = js_array_len(array)
                                .map_err(|error| describe_js_error(&ctx, error))?;
                            if !try_charge_js_elements(locations_len, &materialize_budget) {
                                return Err("query callback hap context.locations array \
                                            too long to read"
                                    .into());
                            }
                            for index in 0..locations_len {
                                let location = match array.get::<rquickjs::Object>(index) {
                                    Ok(location) => location,
                                    Err(error) if matches!(error, rquickjs::Error::Exception) => {
                                        return Err(describe_js_error(&ctx, error));
                                    }
                                    // Holes convert from `undefined` to Object
                                    // with a non-exception error, like the
                                    // hap array above: absent, not a failure.
                                    Err(_) => continue,
                                };
                                let start = location
                                    .get("start")
                                    .map_err(|error| describe_js_error(&ctx, error))?;
                                let end = location
                                    .get("end")
                                    .map_err(|error| describe_js_error(&ctx, error))?;
                                locations.push((start, end));
                            }
                        }
                    }
                    let mut native_hap = Hap::new(whole, sp, value).with_context(locations);
                    // Side-channel context keys (see Hap::edo_size): xen's
                    // combinators talk through hap.context.edoSize, and the
                    // key must survive this crossing like locations do.
                    if let Some(context) = context_value.as_object() {
                        let edo: rquickjs::Value = context
                            .get("edoSize")
                            .map_err(|error| describe_js_error(&ctx, error))?;
                        // edoSize arrives as a regex MATCH - a string
                        // ("31"); numeric use coerces it, so the number is
                        // the faithful carrier.
                        let edo = edo.as_number().or_else(|| {
                            edo.as_string()
                                .and_then(|text| text.to_string().ok())
                                .and_then(|text| text.parse::<f64>().ok())
                        });
                        if let Some(edo) = edo {
                            native_hap = native_hap.with_edo_size_context(edo);
                        }
                        let line: rquickjs::Value = context
                            .get("logLine")
                            .map_err(|error| describe_js_error(&ctx, error))?;
                        if let Some(line) = line.as_string().and_then(|line| line.to_string().ok())
                        {
                            native_hap = native_hap.with_log_line_context(line);
                        }
                    }
                    haps.push(native_hap);
                }
                // The returned hap array is one callback output. Reconcile all
                // value owners before publishing any exclusions from it.
                harvest_sidecars(hap_sidecars).map_err(|error| describe_js_error(&ctx, error))?;
                Ok(haps)
            })
        })
    }
}
