/*
Scale data from @tonaljs/scale-type 4.9.2, used by @tonaljs/tonal 4.10.0.
Copyright (c) 2015 danigb
See crates/core/LICENSE-tonal for the original MIT terms.
*/

//! Generated scale dictionary - do not edit by hand.
//!
//! The @tonaljs/scale-type 4.9.2 dictionary used to resolve scale names such
//! as `.scale("C:major")`.

/// (canonical name, aliases, intervals) in data.ts order.
//
// Deliberately exempt from rustfmt so generated rows retain their stable form.
#[rustfmt::skip]
pub const SCALE_DICTIONARY: &[(&str, &[&str], &[&str])] = &[
    ("major pentatonic", &["pentatonic"], &["1P", "2M", "3M", "5P", "6M"]),
    ("major", &["ionian"], &["1P", "2M", "3M", "4P", "5P", "6M", "7M"]),
    ("minor", &["aeolian"], &["1P", "2M", "3m", "4P", "5P", "6m", "7m"]),
    ("major blues", &[], &["1P", "2M", "3m", "3M", "5P", "6M"]),
    ("minor blues", &["blues"], &["1P", "3m", "4P", "5d", "5P", "7m"]),
    ("melodic minor", &[], &["1P", "2M", "3m", "4P", "5P", "6M", "7M"]),
    ("harmonic minor", &[], &["1P", "2M", "3m", "4P", "5P", "6m", "7M"]),
    ("bebop", &[], &["1P", "2M", "3M", "4P", "5P", "6M", "7m", "7M"]),
    ("diminished", &["whole-half diminished"], &["1P", "2M", "3m", "4P", "5d", "6m", "6M", "7M"]),
    ("dorian", &[], &["1P", "2M", "3m", "4P", "5P", "6M", "7m"]),
    ("lydian", &[], &["1P", "2M", "3M", "4A", "5P", "6M", "7M"]),
    ("mixolydian", &["dominant"], &["1P", "2M", "3M", "4P", "5P", "6M", "7m"]),
    ("phrygian", &[], &["1P", "2m", "3m", "4P", "5P", "6m", "7m"]),
    ("locrian", &[], &["1P", "2m", "3m", "4P", "5d", "6m", "7m"]),
    ("ionian pentatonic", &[], &["1P", "3M", "4P", "5P", "7M"]),
    ("mixolydian pentatonic", &["indian"], &["1P", "3M", "4P", "5P", "7m"]),
    ("ritusen", &[], &["1P", "2M", "4P", "5P", "6M"]),
    ("egyptian", &[], &["1P", "2M", "4P", "5P", "7m"]),
    ("neapolitan major pentatonic", &[], &["1P", "3M", "4P", "5d", "7m"]),
    ("vietnamese 1", &[], &["1P", "3m", "4P", "5P", "6m"]),
    ("pelog", &[], &["1P", "2m", "3m", "5P", "6m"]),
    ("kumoijoshi", &[], &["1P", "2m", "4P", "5P", "6m"]),
    ("hirajoshi", &[], &["1P", "2M", "3m", "5P", "6m"]),
    ("iwato", &[], &["1P", "2m", "4P", "5d", "7m"]),
    ("in-sen", &[], &["1P", "2m", "4P", "5P", "7m"]),
    ("lydian pentatonic", &["chinese"], &["1P", "3M", "4A", "5P", "7M"]),
    ("malkos raga", &[], &["1P", "3m", "4P", "6m", "7m"]),
    ("locrian pentatonic", &["minor seven flat five pentatonic"], &["1P", "3m", "4P", "5d", "7m"]),
    ("minor pentatonic", &["vietnamese 2"], &["1P", "3m", "4P", "5P", "7m"]),
    ("minor six pentatonic", &[], &["1P", "3m", "4P", "5P", "6M"]),
    ("flat three pentatonic", &["kumoi"], &["1P", "2M", "3m", "5P", "6M"]),
    ("flat six pentatonic", &[], &["1P", "2M", "3M", "5P", "6m"]),
    ("scriabin", &[], &["1P", "2m", "3M", "5P", "6M"]),
    ("whole tone pentatonic", &[], &["1P", "3M", "5d", "6m", "7m"]),
    ("lydian #5p pentatonic", &[], &["1P", "3M", "4A", "5A", "7M"]),
    ("lydian dominant pentatonic", &[], &["1P", "3M", "4A", "5P", "7m"]),
    ("minor #7m pentatonic", &[], &["1P", "3m", "4P", "5P", "7M"]),
    ("super locrian pentatonic", &[], &["1P", "3m", "4d", "5d", "7m"]),
    ("minor hexatonic", &[], &["1P", "2M", "3m", "4P", "5P", "7M"]),
    ("augmented", &[], &["1P", "2A", "3M", "5P", "5A", "7M"]),
    ("piongio", &[], &["1P", "2M", "4P", "5P", "6M", "7m"]),
    ("prometheus neapolitan", &[], &["1P", "2m", "3M", "4A", "6M", "7m"]),
    ("prometheus", &[], &["1P", "2M", "3M", "4A", "6M", "7m"]),
    ("mystery #1", &[], &["1P", "2m", "3M", "5d", "6m", "7m"]),
    ("six tone symmetric", &[], &["1P", "2m", "3M", "4P", "5A", "6M"]),
    ("whole tone", &["messiaen's mode #1"], &["1P", "2M", "3M", "4A", "5A", "6A"]),
    ("messiaen's mode #5", &[], &["1P", "2m", "4P", "4A", "5P", "7M"]),
    ("locrian major", &["arabian"], &["1P", "2M", "3M", "4P", "5d", "6m", "7m"]),
    ("double harmonic lydian", &[], &["1P", "2m", "3M", "4A", "5P", "6m", "7M"]),
    ("altered", &["super locrian", "diminished whole tone", "pomeroy"], &["1P", "2m", "2A", "3M", "4A", "6m", "7m"]),
    ("locrian #2", &["half-diminished", "aeolian b5"], &["1P", "2M", "3m", "4P", "5d", "6m", "7m"]),
    ("mixolydian b6", &["melodic minor fifth mode", "hindu"], &["1P", "2M", "3M", "4P", "5P", "6m", "7m"]),
    ("lydian dominant", &["lydian b7", "overtone"], &["1P", "2M", "3M", "4A", "5P", "6M", "7m"]),
    ("lydian augmented", &[], &["1P", "2M", "3M", "4A", "5A", "6M", "7M"]),
    ("dorian b2", &["phrygian #6", "melodic minor second mode"], &["1P", "2m", "3m", "4P", "5P", "6M", "7m"]),
    ("ultralocrian", &["superlocrian bb7", "superlocrian diminished"], &["1P", "2m", "3m", "4d", "5d", "6m", "7d"]),
    ("locrian 6", &["locrian natural 6", "locrian sharp 6"], &["1P", "2m", "3m", "4P", "5d", "6M", "7m"]),
    ("augmented heptatonic", &[], &["1P", "2A", "3M", "4P", "5P", "5A", "7M"]),
    ("dorian #4", &["ukrainian dorian", "romanian minor", "altered dorian"], &["1P", "2M", "3m", "4A", "5P", "6M", "7m"]),
    ("lydian diminished", &[], &["1P", "2M", "3m", "4A", "5P", "6M", "7M"]),
    ("leading whole tone", &[], &["1P", "2M", "3M", "4A", "5A", "7m", "7M"]),
    ("lydian minor", &[], &["1P", "2M", "3M", "4A", "5P", "6m", "7m"]),
    ("phrygian dominant", &["spanish", "phrygian major"], &["1P", "2m", "3M", "4P", "5P", "6m", "7m"]),
    ("balinese", &[], &["1P", "2m", "3m", "4P", "5P", "6m", "7M"]),
    ("neapolitan major", &[], &["1P", "2m", "3m", "4P", "5P", "6M", "7M"]),
    ("harmonic major", &[], &["1P", "2M", "3M", "4P", "5P", "6m", "7M"]),
    ("double harmonic major", &["gypsy"], &["1P", "2m", "3M", "4P", "5P", "6m", "7M"]),
    ("hungarian minor", &[], &["1P", "2M", "3m", "4A", "5P", "6m", "7M"]),
    ("hungarian major", &[], &["1P", "2A", "3M", "4A", "5P", "6M", "7m"]),
    ("oriental", &[], &["1P", "2m", "3M", "4P", "5d", "6M", "7m"]),
    ("flamenco", &[], &["1P", "2m", "3m", "3M", "4A", "5P", "7m"]),
    ("todi raga", &[], &["1P", "2m", "3m", "4A", "5P", "6m", "7M"]),
    ("persian", &[], &["1P", "2m", "3M", "4P", "5d", "6m", "7M"]),
    ("enigmatic", &[], &["1P", "2m", "3M", "5d", "6m", "7m", "7M"]),
    ("major augmented", &["major #5", "ionian augmented", "ionian #5"], &["1P", "2M", "3M", "4P", "5A", "6M", "7M"]),
    ("lydian #9", &[], &["1P", "2A", "3M", "4A", "5P", "6M", "7M"]),
    ("messiaen's mode #4", &[], &["1P", "2m", "2M", "4P", "4A", "5P", "6m", "7M"]),
    ("purvi raga", &[], &["1P", "2m", "3M", "4P", "4A", "5P", "6m", "7M"]),
    ("spanish heptatonic", &[], &["1P", "2m", "3m", "3M", "4P", "5P", "6m", "7m"]),
    ("bebop minor", &[], &["1P", "2M", "3m", "3M", "4P", "5P", "6M", "7m"]),
    ("bebop major", &[], &["1P", "2M", "3M", "4P", "5P", "5A", "6M", "7M"]),
    ("bebop locrian", &[], &["1P", "2m", "3m", "4P", "5d", "5P", "6m", "7m"]),
    ("minor bebop", &[], &["1P", "2M", "3m", "4P", "5P", "6m", "7m", "7M"]),
    ("ichikosucho", &[], &["1P", "2M", "3M", "4P", "5d", "5P", "6M", "7M"]),
    ("minor six diminished", &[], &["1P", "2M", "3m", "4P", "5P", "6m", "6M", "7M"]),
    ("half-whole diminished", &["dominant diminished", "messiaen's mode #2"], &["1P", "2m", "3m", "3M", "4A", "5P", "6M", "7m"]),
    ("kafi raga", &[], &["1P", "3m", "3M", "4P", "5P", "6M", "7m", "7M"]),
    ("messiaen's mode #6", &[], &["1P", "2M", "3M", "4P", "4A", "5A", "6A", "7M"]),
    ("composite blues", &[], &["1P", "2M", "3m", "3M", "4P", "5d", "5P", "6M", "7m"]),
    ("messiaen's mode #3", &[], &["1P", "2M", "3m", "3M", "4A", "5P", "6m", "7m", "7M"]),
    ("messiaen's mode #7", &[], &["1P", "2m", "2M", "3m", "4P", "4A", "5P", "6m", "6M", "7M"]),
    ("chromatic", &[], &["1P", "2m", "2M", "3m", "3M", "4P", "5d", "5P", "6m", "6M", "7m", "7M"]),
];

// ---------------------------------------------------------------------------
// The scale catalogue's reference entries.
//
// One entry per scale the dictionary resolves, documented where the
// dictionary lives; aliases ride as synonyms, so every spelling
// scale("C:…") accepts is documented too.
// ---------------------------------------------------------------------------

use crate::reference::ReferenceEntry;

/// One entry per scale, in the dictionary's own order.
pub static SCALE_REFERENCE: &[ReferenceEntry] = &[
    ReferenceEntry {
        name: "major pentatonic",
        synonyms: &["pentatonic"],
        summary: "the major pentatonic scale",
        description: "Five notes with no semitones - the impossible-to-play-wrong scale of folk, country and rock. Steps: the root, a 2nd, a major 3rd, a 5th, a 6th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "major",
        synonyms: &["ionian"],
        summary: "the major scale",
        description: "The default of western harmony - bright and resolved; everything else is heard against it. Steps: the root, a 2nd, a major 3rd, a 4th, a 5th, a 6th, a major 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "minor",
        synonyms: &["aeolian"],
        summary: "the minor scale",
        description: "The natural minor - dark and settled. Steps: the root, a 2nd, a minor 3rd, a 4th, a 5th, a minor 6th, a minor 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "major blues",
        synonyms: &[],
        summary: "the major blues scale",
        description: "The major pentatonic with a blue note. Steps: the root, a 2nd, a minor 3rd, a major 3rd, a 5th, a 6th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "minor blues",
        synonyms: &["blues"],
        summary: "the minor blues scale",
        description: "The minor pentatonic with the blue note added. Steps: the root, a minor 3rd, a 4th, a flat 5th, a 5th, a minor 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "melodic minor",
        synonyms: &[],
        summary: "the melodic minor scale",
        description: "Minor with raised sixth and seventh - the jazz minor. Steps: the root, a 2nd, a minor 3rd, a 4th, a 5th, a 6th, a major 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "harmonic minor",
        synonyms: &[],
        summary: "the harmonic minor scale",
        description: "Natural minor with a raised seventh - dramatic, classical, middle-eastern. Steps: the root, a 2nd, a minor 3rd, a 4th, a 5th, a minor 6th, a major 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "bebop",
        synonyms: &[],
        summary: "the bebop scale",
        description: "A bebop scale - a passing tone added so chord tones land on the beats. Steps: the root, a 2nd, a major 3rd, a 4th, a 5th, a 6th, a minor 7th, a major 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "diminished",
        synonyms: &["whole-half diminished"],
        summary: "the diminished scale",
        description: "Alternating whole and half steps - symmetric tension. Steps: the root, a 2nd, a minor 3rd, a 4th, a flat 5th, a minor 6th, a 6th, a major 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "dorian",
        synonyms: &[],
        summary: "the dorian scale",
        description: "Minor with a raised sixth - the bright minor of funk and modal jazz. Steps: the root, a 2nd, a minor 3rd, a 4th, a 5th, a 6th, a minor 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "lydian",
        synonyms: &[],
        summary: "the lydian scale",
        description: "Major with a sharp fourth - floaty and filmic. Steps: the root, a 2nd, a major 3rd, a sharp 4th, a 5th, a 6th, a major 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "mixolydian",
        synonyms: &["dominant"],
        summary: "the mixolydian scale",
        description: "Major with a flat seventh - the dominant mode; blues and funk. Steps: the root, a 2nd, a major 3rd, a 4th, a 5th, a 6th, a minor 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "phrygian",
        synonyms: &[],
        summary: "the phrygian scale",
        description: "Minor with a flat second - dark, Spanish and metal. Steps: the root, a flat 2nd, a minor 3rd, a 4th, a 5th, a minor 6th, a minor 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "locrian",
        synonyms: &[],
        summary: "the locrian scale",
        description: "The diminished mode - unstable, more theory than song. Steps: the root, a flat 2nd, a minor 3rd, a 4th, a flat 5th, a minor 6th, a minor 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "ionian pentatonic",
        synonyms: &[],
        summary: "the ionian pentatonic scale",
        description: "A 5-note scale. Steps: the root, a major 3rd, a 4th, a 5th, a major 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "mixolydian pentatonic",
        synonyms: &["indian"],
        summary: "the mixolydian pentatonic scale",
        description: "A 5-note scale. Steps: the root, a major 3rd, a 4th, a 5th, a minor 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "ritusen",
        synonyms: &[],
        summary: "the ritusen scale",
        description: "A suspended pentatonic - no third. Steps: the root, a 2nd, a 4th, a 5th, a 6th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "egyptian",
        synonyms: &[],
        summary: "the egyptian scale",
        description: "A suspended pentatonic - no third, open and ancient. Steps: the root, a 2nd, a 4th, a 5th, a minor 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "neapolitan major pentatonic",
        synonyms: &[],
        summary: "the neapolitan major pentatonic scale",
        description: "A 5-note scale. Steps: the root, a major 3rd, a 4th, a flat 5th, a minor 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "vietnamese 1",
        synonyms: &[],
        summary: "the vietnamese 1 scale",
        description: "A 5-note scale. Steps: the root, a minor 3rd, a 4th, a 5th, a minor 6th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "pelog",
        synonyms: &[],
        summary: "the pelog scale",
        description: "A 5-note scale. Steps: the root, a flat 2nd, a minor 3rd, a 5th, a minor 6th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "kumoijoshi",
        synonyms: &[],
        summary: "the kumoijoshi scale",
        description: "A Japanese koto tuning. Steps: the root, a flat 2nd, a 4th, a 5th, a minor 6th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "hirajoshi",
        synonyms: &[],
        summary: "the hirajoshi scale",
        description: "A Japanese koto tuning. Steps: the root, a 2nd, a minor 3rd, a 5th, a minor 6th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "iwato",
        synonyms: &[],
        summary: "the iwato scale",
        description: "A Japanese koto tuning. Steps: the root, a flat 2nd, a 4th, a flat 5th, a minor 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "in-sen",
        synonyms: &[],
        summary: "the in-sen scale",
        description: "A Japanese koto tuning. Steps: the root, a flat 2nd, a 4th, a 5th, a minor 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "lydian pentatonic",
        synonyms: &["chinese"],
        summary: "the lydian pentatonic scale",
        description: "A 5-note scale. Steps: the root, a major 3rd, a sharp 4th, a 5th, a major 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "malkos raga",
        synonyms: &[],
        summary: "the malkos raga scale",
        description: "A 5-note scale. Steps: the root, a minor 3rd, a 4th, a minor 6th, a minor 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "locrian pentatonic",
        synonyms: &["minor seven flat five pentatonic"],
        summary: "the locrian pentatonic scale",
        description: "A 5-note scale. Steps: the root, a minor 3rd, a 4th, a flat 5th, a minor 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "minor pentatonic",
        synonyms: &["vietnamese 2"],
        summary: "the minor pentatonic scale",
        description: "The blues and rock solo workhorse. Steps: the root, a minor 3rd, a 4th, a 5th, a minor 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "minor six pentatonic",
        synonyms: &[],
        summary: "the minor six pentatonic scale",
        description: "A 5-note scale. Steps: the root, a minor 3rd, a 4th, a 5th, a 6th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "flat three pentatonic",
        synonyms: &["kumoi"],
        summary: "the flat three pentatonic scale",
        description: "A 5-note scale. Steps: the root, a 2nd, a minor 3rd, a 5th, a 6th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "flat six pentatonic",
        synonyms: &[],
        summary: "the flat six pentatonic scale",
        description: "A 5-note scale. Steps: the root, a 2nd, a major 3rd, a 5th, a minor 6th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "scriabin",
        synonyms: &[],
        summary: "the scriabin scale",
        description: "Scriabin's mystic chord - the synthetic scale. Steps: the root, a flat 2nd, a major 3rd, a 5th, a 6th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "whole tone pentatonic",
        synonyms: &[],
        summary: "the whole tone pentatonic scale",
        description: "A 5-note scale. Steps: the root, a major 3rd, a flat 5th, a minor 6th, a minor 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "lydian #5p pentatonic",
        synonyms: &[],
        summary: "the lydian #5p pentatonic scale",
        description: "A 5-note scale. Steps: the root, a major 3rd, a sharp 4th, a sharp 5th, a major 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "lydian dominant pentatonic",
        synonyms: &[],
        summary: "the lydian dominant pentatonic scale",
        description: "A 5-note scale. Steps: the root, a major 3rd, a sharp 4th, a 5th, a minor 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "minor #7m pentatonic",
        synonyms: &[],
        summary: "the minor #7m pentatonic scale",
        description: "A 5-note scale. Steps: the root, a minor 3rd, a 4th, a 5th, a major 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "super locrian pentatonic",
        synonyms: &[],
        summary: "the super locrian pentatonic scale",
        description: "A 5-note scale. Steps: the root, a minor 3rd, a flat 4th, a flat 5th, a minor 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "minor hexatonic",
        synonyms: &[],
        summary: "the minor hexatonic scale",
        description: "A 6-note scale. Steps: the root, a 2nd, a minor 3rd, a 4th, a 5th, a major 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "augmented",
        synonyms: &[],
        summary: "the augmented scale",
        description: "The augmented colour - symmetric, whole-tone-adjacent. Steps: the root, a sharp 2nd, a major 3rd, a 5th, a sharp 5th, a major 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "piongio",
        synonyms: &[],
        summary: "the piongio scale",
        description: "A 6-note scale. Steps: the root, a 2nd, a 4th, a 5th, a 6th, a minor 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "prometheus neapolitan",
        synonyms: &[],
        summary: "the prometheus neapolitan scale",
        description: "A 6-note scale. Steps: the root, a flat 2nd, a major 3rd, a sharp 4th, a 6th, a minor 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "prometheus",
        synonyms: &[],
        summary: "the prometheus scale",
        description: "Scriabin's prometheus scale. Steps: the root, a 2nd, a major 3rd, a sharp 4th, a 6th, a minor 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "mystery #1",
        synonyms: &[],
        summary: "the mystery #1 scale",
        description: "A 6-note scale. Steps: the root, a flat 2nd, a major 3rd, a flat 5th, a minor 6th, a minor 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "six tone symmetric",
        synonyms: &[],
        summary: "the six tone symmetric scale",
        description: "A 6-note scale. Steps: the root, a flat 2nd, a major 3rd, a 4th, a sharp 5th, a 6th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "whole tone",
        synonyms: &["messiaen's mode #1"],
        summary: "the whole tone scale",
        description: "All whole tones - no leading note, the dream effect. Steps: the root, a 2nd, a major 3rd, a sharp 4th, a sharp 5th, a sharp 6th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "messiaen's mode #5",
        synonyms: &[],
        summary: "the messiaen's mode #5 scale",
        description: "Messiaen's fifth mode of limited transposition. Steps: the root, a flat 2nd, a 4th, a sharp 4th, a 5th, a major 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "locrian major",
        synonyms: &["arabian"],
        summary: "the locrian major scale",
        description: "Locrian with a major third - the arabian scale. Steps: the root, a 2nd, a major 3rd, a 4th, a flat 5th, a minor 6th, a minor 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "double harmonic lydian",
        synonyms: &[],
        summary: "the double harmonic lydian scale",
        description: "The double-harmonic family - two augmented seconds. Steps: the root, a flat 2nd, a major 3rd, a sharp 4th, a 5th, a minor 6th, a major 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "altered",
        synonyms: &["super locrian", "diminished whole tone", "pomeroy"],
        summary: "the altered scale",
        description: "Every altered tension over a dominant - flat nine, sharp nine, sharp eleven, flat thirteen. Steps: the root, a flat 2nd, a sharp 2nd, a major 3rd, a sharp 4th, a minor 6th, a minor 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "locrian #2",
        synonyms: &["half-diminished", "aeolian b5"],
        summary: "the locrian #2 scale",
        description: "A 7-note scale. Steps: the root, a 2nd, a minor 3rd, a 4th, a flat 5th, a minor 6th, a minor 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "mixolydian b6",
        synonyms: &["melodic minor fifth mode", "hindu"],
        summary: "the mixolydian b6 scale",
        description: "A 7-note scale. Steps: the root, a 2nd, a major 3rd, a 4th, a 5th, a minor 6th, a minor 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "lydian dominant",
        synonyms: &["lydian b7", "overtone"],
        summary: "the lydian dominant scale",
        description: "Lydian with a flat seventh - the sharp-eleven dominant sound. Steps: the root, a 2nd, a major 3rd, a sharp 4th, a 5th, a 6th, a minor 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "lydian augmented",
        synonyms: &[],
        summary: "the lydian augmented scale",
        description: "A 7-note scale. Steps: the root, a 2nd, a major 3rd, a sharp 4th, a sharp 5th, a 6th, a major 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "dorian b2",
        synonyms: &["phrygian #6", "melodic minor second mode"],
        summary: "the dorian b2 scale",
        description: "A 7-note scale. Steps: the root, a flat 2nd, a minor 3rd, a 4th, a 5th, a 6th, a minor 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "ultralocrian",
        synonyms: &["superlocrian bb7", "superlocrian diminished"],
        summary: "the ultralocrian scale",
        description: "A 7-note scale. Steps: the root, a flat 2nd, a minor 3rd, a flat 4th, a flat 5th, a minor 6th, a diminished 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "locrian 6",
        synonyms: &["locrian natural 6", "locrian sharp 6"],
        summary: "the locrian 6 scale",
        description: "A 7-note scale. Steps: the root, a flat 2nd, a minor 3rd, a 4th, a flat 5th, a 6th, a minor 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "augmented heptatonic",
        synonyms: &[],
        summary: "the augmented heptatonic scale",
        description: "A 7-note scale. Steps: the root, a sharp 2nd, a major 3rd, a 4th, a 5th, a sharp 5th, a major 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "dorian #4",
        synonyms: &["ukrainian dorian", "romanian minor", "altered dorian"],
        summary: "the dorian #4 scale",
        description: "A 7-note scale. Steps: the root, a 2nd, a minor 3rd, a sharp 4th, a 5th, a 6th, a minor 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "lydian diminished",
        synonyms: &[],
        summary: "the lydian diminished scale",
        description: "A 7-note scale. Steps: the root, a 2nd, a minor 3rd, a sharp 4th, a 5th, a 6th, a major 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "leading whole tone",
        synonyms: &[],
        summary: "the leading whole tone scale",
        description: "A 7-note scale. Steps: the root, a 2nd, a major 3rd, a sharp 4th, a sharp 5th, a minor 7th, a major 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "lydian minor",
        synonyms: &[],
        summary: "the lydian minor scale",
        description: "A 7-note scale. Steps: the root, a 2nd, a major 3rd, a sharp 4th, a 5th, a minor 6th, a minor 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "phrygian dominant",
        synonyms: &["spanish", "phrygian major"],
        summary: "the phrygian dominant scale",
        description: "Phrygian with a major third - flamenco and middle-eastern dominant. Steps: the root, a flat 2nd, a major 3rd, a 4th, a 5th, a minor 6th, a minor 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "balinese",
        synonyms: &[],
        summary: "the balinese scale",
        description: "A 7-note scale. Steps: the root, a flat 2nd, a minor 3rd, a 4th, a 5th, a minor 6th, a major 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "neapolitan major",
        synonyms: &[],
        summary: "the neapolitan major scale",
        description: "A 7-note scale. Steps: the root, a flat 2nd, a minor 3rd, a 4th, a 5th, a 6th, a major 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "harmonic major",
        synonyms: &[],
        summary: "the harmonic major scale",
        description: "Major with a flat sixth - major's dramatic sibling. Steps: the root, a 2nd, a major 3rd, a 4th, a 5th, a minor 6th, a major 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "double harmonic major",
        synonyms: &["gypsy"],
        summary: "the double harmonic major scale",
        description: "A 7-note scale. Steps: the root, a flat 2nd, a major 3rd, a 4th, a 5th, a minor 6th, a major 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "hungarian minor",
        synonyms: &[],
        summary: "the hungarian minor scale",
        description: "The gypsy-minor colour - raised fourth and raised seventh. Steps: the root, a 2nd, a minor 3rd, a sharp 4th, a 5th, a minor 6th, a major 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "hungarian major",
        synonyms: &[],
        summary: "the hungarian major scale",
        description: "A 7-note scale. Steps: the root, a sharp 2nd, a major 3rd, a sharp 4th, a 5th, a 6th, a minor 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "oriental",
        synonyms: &[],
        summary: "the oriental scale",
        description: "A 7-note scale. Steps: the root, a flat 2nd, a major 3rd, a 4th, a flat 5th, a 6th, a minor 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "flamenco",
        synonyms: &[],
        summary: "the flamenco scale",
        description: "The flamenco colour. Steps: the root, a flat 2nd, a minor 3rd, a major 3rd, a sharp 4th, a 5th, a minor 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "todi raga",
        synonyms: &[],
        summary: "the todi raga scale",
        description: "A 7-note scale. Steps: the root, a flat 2nd, a minor 3rd, a sharp 4th, a 5th, a minor 6th, a major 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "persian",
        synonyms: &[],
        summary: "the persian scale",
        description: "A 7-note scale. Steps: the root, a flat 2nd, a major 3rd, a 4th, a flat 5th, a minor 6th, a major 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "enigmatic",
        synonyms: &[],
        summary: "the enigmatic scale",
        description: "A 7-note scale. Steps: the root, a flat 2nd, a major 3rd, a flat 5th, a minor 6th, a minor 7th, a major 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "major augmented",
        synonyms: &["major #5", "ionian augmented", "ionian #5"],
        summary: "the major augmented scale",
        description: "A 7-note scale. Steps: the root, a 2nd, a major 3rd, a 4th, a sharp 5th, a 6th, a major 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "lydian #9",
        synonyms: &[],
        summary: "the lydian #9 scale",
        description: "A 7-note scale. Steps: the root, a sharp 2nd, a major 3rd, a sharp 4th, a 5th, a 6th, a major 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "messiaen's mode #4",
        synonyms: &[],
        summary: "the messiaen's mode #4 scale",
        description: "A 8-note scale. Steps: the root, a flat 2nd, a 2nd, a 4th, a sharp 4th, a 5th, a minor 6th, a major 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "purvi raga",
        synonyms: &[],
        summary: "the purvi raga scale",
        description: "A 8-note scale. Steps: the root, a flat 2nd, a major 3rd, a 4th, a sharp 4th, a 5th, a minor 6th, a major 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "spanish heptatonic",
        synonyms: &[],
        summary: "the spanish heptatonic scale",
        description: "A 8-note scale. Steps: the root, a flat 2nd, a minor 3rd, a major 3rd, a 4th, a 5th, a minor 6th, a minor 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "bebop minor",
        synonyms: &[],
        summary: "the bebop minor scale",
        description: "A bebop scale - a passing tone added so chord tones land on the beats. Steps: the root, a 2nd, a minor 3rd, a major 3rd, a 4th, a 5th, a 6th, a minor 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "bebop major",
        synonyms: &[],
        summary: "the bebop major scale",
        description: "A bebop scale - a passing tone added so chord tones land on the beats. Steps: the root, a 2nd, a major 3rd, a 4th, a 5th, a sharp 5th, a 6th, a major 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "bebop locrian",
        synonyms: &[],
        summary: "the bebop locrian scale",
        description: "A 8-note scale. Steps: the root, a flat 2nd, a minor 3rd, a 4th, a flat 5th, a 5th, a minor 6th, a minor 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "minor bebop",
        synonyms: &[],
        summary: "the minor bebop scale",
        description: "A 8-note scale. Steps: the root, a 2nd, a minor 3rd, a 4th, a 5th, a minor 6th, a minor 7th, a major 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "ichikosucho",
        synonyms: &[],
        summary: "the ichikosucho scale",
        description: "A 8-note scale. Steps: the root, a 2nd, a major 3rd, a 4th, a flat 5th, a 5th, a 6th, a major 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "minor six diminished",
        synonyms: &[],
        summary: "the minor six diminished scale",
        description: "A 8-note scale. Steps: the root, a 2nd, a minor 3rd, a 4th, a 5th, a minor 6th, a 6th, a major 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "half-whole diminished",
        synonyms: &["dominant diminished", "messiaen's mode #2"],
        summary: "the half-whole diminished scale",
        description: "A 8-note scale. Steps: the root, a flat 2nd, a minor 3rd, a major 3rd, a sharp 4th, a 5th, a 6th, a minor 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "kafi raga",
        synonyms: &[],
        summary: "the kafi raga scale",
        description: "A 8-note scale. Steps: the root, a minor 3rd, a major 3rd, a 4th, a 5th, a 6th, a minor 7th, a major 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "messiaen's mode #6",
        synonyms: &[],
        summary: "the messiaen's mode #6 scale",
        description: "A 8-note scale. Steps: the root, a 2nd, a major 3rd, a 4th, a sharp 4th, a sharp 5th, a sharp 6th, a major 7th.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "composite blues",
        synonyms: &[],
        summary: "the composite blues scale",
        description: "A 9-note scale. Steps: 9 notes - too many to recite; hear it.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "messiaen's mode #3",
        synonyms: &[],
        summary: "the messiaen's mode #3 scale",
        description: "A 9-note scale. Steps: 9 notes - too many to recite; hear it.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "messiaen's mode #7",
        synonyms: &[],
        summary: "the messiaen's mode #7 scale",
        description: "A 10-note scale. Steps: 10 notes - too many to recite; hear it.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
    ReferenceEntry {
        name: "chromatic",
        synonyms: &[],
        summary: "the chromatic scale",
        description: "All twelve semitones - every note there is. Steps: 12 notes - too many to recite; hear it.",
        params: &[],
        examples: &[],
        tags: &["scale"],
        no_autocomplete: false,
        deprecated: false,
        origin: "rustel",
    },
];
